# Generated by Django 4.2.3 on 2023-07-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_department_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('None', 'None'), ('BIO', 'BIO'), ('IS', 'IS'), ('CS', 'CS')], max_length=10, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instructor_salary',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='salary'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.CharField(choices=[('3', '3'), ('1', '1'), ('2', '2'), ('4', '4')], max_length=1, verbose_name='level'),
        ),
    ]
