# Generated by Django 4.1.7 on 2023-07-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_department_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('None', 'None'), ('BIO', 'BIO'), ('IS', 'IS'), ('CS', 'CS')], max_length=10, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_GPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_address',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_age',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, verbose_name='level'),
        ),
    ]
