# Generated by Django 4.1.7 on 2023-07-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_department_department_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cousre',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('CS', 'CS'), ('None', 'None'), ('BIO', 'BIO'), ('IS', 'IS')], max_length=10, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('1', '1'), ('4', '4')], max_length=1, verbose_name='level'),
        ),
    ]
