# Generated by Django 4.2.3 on 2023-07-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_cousre_student_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_score',
        ),
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('None', 'None'), ('CS', 'CS'), ('BIO', 'BIO'), ('IS', 'IS')], max_length=10, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('2', '2'), ('1', '1')], max_length=1, verbose_name='level'),
        ),
    ]
