# Generated by Django 4.2.3 on 2023-07-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_course_course_score_student_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('CS', 'CS'), ('None', 'None'), ('IS', 'IS'), ('BIO', 'BIO')], max_length=10, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.CharField(choices=[('1', '1'), ('4', '4'), ('3', '3'), ('2', '2')], max_length=1, verbose_name='level'),
        ),
    ]
