# Generated by Django 4.2.3 on 2023-07-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_department_department_name_alter_student_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('CS', 'CS'), ('None', 'None'), ('BIO', 'BIO'), ('IS', 'IS')], max_length=10, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_GPA',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.CharField(choices=[('2', '2'), ('1', '1'), ('4', '4'), ('3', '3')], max_length=1, verbose_name='level'),
        ),
    ]
