# Generated by Django 4.2.3 on 2023-07-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_department_department_name_alter_student_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('IS', 'IS'), ('None', 'None'), ('CS', 'CS'), ('BIO', 'BIO')], max_length=10, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.CharField(blank=True, choices=[('absent', 'absent'), ('attend', 'attend')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('1', '1'), ('4', '4')], max_length=1, verbose_name='level'),
        ),
    ]
