# Generated by Django 4.2.3 on 2023-07-24 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_alter_department_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('BIO', 'BIO'), ('CS', 'CS'), ('IS', 'IS'), ('None', 'None')], max_length=10, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.CharField(blank=True, choices=[('attend', 'attend'), ('absent', 'absent')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, verbose_name='level'),
        ),
    ]
