# Generated by Django 4.2.3 on 2023-07-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_department_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '4'), ('3', '3')], max_length=1, verbose_name='level'),
        ),
    ]
