# Generated by Django 4.2.3 on 2023-07-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_student_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.CharField(choices=[('4', '4'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='level'),
        ),
    ]
