# Generated by Django 4.2.3 on 2023-07-24 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_student_student_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.CharField(blank=True, choices=[('attend', 'attend'), ('absent', 'absent')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.CharField(choices=[('3', '3'), ('1', '1'), ('4', '4'), ('2', '2')], max_length=1, verbose_name='level'),
        ),
    ]
