# Generated by Django 4.2.3 on 2023-07-24 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0017_remove_student_course_course_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('CS', 'CS'), ('None', 'None'), ('IS', 'IS'), ('BIO', 'BIO')], max_length=10, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('1', '1'), ('2', '2')], max_length=1, verbose_name='level'),
        ),
    ]
