# Generated by Django 4.2.3 on 2023-07-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_student_student_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.CharField(blank=True, choices=[('absent', 'absent'), ('attend', 'attend')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('IS', 'IS'), ('CS', 'CS'), ('None', 'None'), ('BIO', 'BIO')], default='', max_length=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
