# Generated by Django 4.2.3 on 2023-07-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_student_attendance_alter_student_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='student_courses',
            field=models.ManyToManyField(to='api.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.CharField(blank=True, choices=[('attend', 'attend'), ('absent', 'absent')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('IS', 'IS'), ('CS', 'CS'), ('BIO', 'BIO'), ('None', 'None')], max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('3', '3'), ('1', '1')], max_length=1, verbose_name='level'),
        ),
    ]
