# Generated by Django 4.2.3 on 2023-07-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_course_student_student_student_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_courses',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='student', to='api.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.CharField(blank=True, choices=[('absent', 'absent'), ('attend', 'attend')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('IS', 'IS'), ('CS', 'CS'), ('None', 'None'), ('BIO', 'BIO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.CharField(choices=[('4', '4'), ('1', '1'), ('3', '3'), ('2', '2')], max_length=1, verbose_name='level'),
        ),
    ]
