# Generated by Django 4.2.3 on 2023-07-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_student_attendance_alter_student_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('IS', 'IS'), ('None', 'None'), ('CS', 'CS'), ('BIO', 'BIO')], max_length=5),
        ),
    ]
