# Generated by Django 4.2.3 on 2023-07-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CS', 'CS'), ('IS', 'IS'), ('None', 'None'), ('BIO', 'BIO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=1, verbose_name='level'),
        ),
    ]
