# Generated by Django 4.2.3 on 2023-07-24 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0027_remove_grade_user_remove_student_student_gpa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.AddField(
            model_name='grade',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CS', 'CS'), ('IS', 'IS'), ('BIO', 'BIO'), ('None', 'None')], max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('1', '1'), ('4', '4')], max_length=1, verbose_name='level'),
        ),
    ]
