# Generated by Django 4.2.3 on 2023-07-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_grade_student_grade_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('None', 'None'), ('IS', 'IS'), ('BIO', 'BIO'), ('CS', 'CS')], max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.CharField(choices=[('3', '3'), ('1', '1'), ('2', '2'), ('4', '4')], max_length=1, verbose_name='level'),
        ),
    ]
