# Generated by Django 4.2.3 on 2023-07-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_instructor_image_instructor_material_student_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='GPA',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CS', 'CS'), ('None', 'None'), ('IS', 'IS'), ('BIO', 'BIO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.CharField(choices=[('1', '1'), ('4', '4'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='level'),
        ),
    ]
